env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/typescript
  - prettier
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - plugin:node/recommended
  - plugin:jsdoc/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  impliedStrict: true
  sourceType: module
  project: ./tsconfig.json
rules:
  linebreak-style:
    - error
    - unix
  prettier/prettier:
    - error
    -
      semi: false
      singleQuote: true
      printWidth: 120
  node/no-unsupported-features/es-syntax: 0
settings:
  node:
    tryExtensions:
      - .ts
      - .js
plugins:
  - jsdoc
  - ava
  - '@typescript-eslint'
  - prettier
