env:
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:jsdoc/recommended'
  - 'plugin:ava/recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
plugins:
  - jsdoc
  - ava
